version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint*'
          - 'prettier'
          - 'vitest*'
          - '@vitest/*'
          - 'tsup'
          - 'husky'
          - 'lint-staged'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # Keep GitHub Actions up to date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
    commit-message:
      prefix: 'ci'
      include: 'scope'
