/**
 * Error codes for the Solana SDK.
 */
export const SolanaErrorCodes = {
  // Original error codes
  INVALID_KEYPAIR: 'INVALID_KEYPAIR',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  RPC_ERROR: 'RPC_ERROR',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

  // RPC-specific error codes
  RPC_PARSE_ERROR: 'RPC_PARSE_ERROR',
  RPC_INVALID_REQUEST: 'RPC_INVALID_REQUEST',
  RPC_METHOD_NOT_FOUND: 'RPC_METHOD_NOT_FOUND',
  RPC_INVALID_PARAMS: 'RPC_INVALID_PARAMS',
  RPC_INTERNAL_ERROR: 'RPC_INTERNAL_ERROR',
  RPC_SERVER_ERROR: 'RPC_SERVER_ERROR',
  RPC_TRANSACTION_PRECOMPILE_VERIFICATION_FAILURE:
    'RPC_TRANSACTION_PRECOMPILE_VERIFICATION_FAILURE',
  RPC_BLOCKHASH_NOT_FOUND: 'RPC_BLOCKHASH_NOT_FOUND',
  RPC_SLOT_SKIPPED: 'RPC_SLOT_SKIPPED',
  RPC_NO_HEALTHY_CONNECTION: 'RPC_NO_HEALTHY_CONNECTION',

  // Validation error codes
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  INVALID_SIGNATURE_LENGTH: 'INVALID_SIGNATURE_LENGTH',
  INVALID_ADDRESS_LENGTH: 'INVALID_ADDRESS_LENGTH',
  INVALID_ADDRESS_FORMAT: 'INVALID_ADDRESS_FORMAT',
  TRANSACTION_TOO_LARGE: 'TRANSACTION_TOO_LARGE',
  INSUFFICIENT_SIGNATURES: 'INSUFFICIENT_SIGNATURES',
  DUPLICATE_SIGNATURE: 'DUPLICATE_SIGNATURE',
  INVALID_ACCOUNT_INDEX: 'INVALID_ACCOUNT_INDEX',
  INVALID_INSTRUCTION_DATA: 'INVALID_INSTRUCTION_DATA',

  // Network and connection errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  CONNECTION_ERROR: 'CONNECTION_ERROR',

  // Transaction simulation and enhancement errors
  SIMULATION_FAILED: 'SIMULATION_FAILED',
  PREFLIGHT_FAILURE: 'PREFLIGHT_FAILURE',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  PROGRAM_ERROR: 'PROGRAM_ERROR',

  // Cryptographic errors
  CRYPTO_NOT_SUPPORTED: 'CRYPTO_NOT_SUPPORTED',
  KEY_GENERATION_FAILED: 'KEY_GENERATION_FAILED',
  INVALID_KEY_OPTIONS: 'INVALID_KEY_OPTIONS',
  KEY_EXTRACTION_FAILED: 'KEY_EXTRACTION_FAILED',
  INVALID_KEY_TYPE: 'INVALID_KEY_TYPE',
} as const;

/**
 * Type for Solana error codes.
 */
export type SolanaErrorCode = (typeof SolanaErrorCodes)[keyof typeof SolanaErrorCodes];
