/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WalletTestImport } from './routes/wallet-test'
import { Route as MinimalImport } from './routes/minimal'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

// Create/Update Routes

const WalletTestRoute = WalletTestImport.update({
  path: '/wallet-test',
  getParentRoute: () => rootRoute,
} as any)

const MinimalRoute = MinimalImport.update({
  path: '/minimal',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/minimal': {
      id: '/minimal'
      path: '/minimal'
      fullPath: '/minimal'
      preLoaderRoute: typeof MinimalImport
      parentRoute: typeof rootRoute
    }
    '/wallet-test': {
      id: '/wallet-test'
      path: '/wallet-test'
      fullPath: '/wallet-test'
      preLoaderRoute: typeof WalletTestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, MinimalRoute, WalletTestRoute })

/* prettier-ignore-end */